channels = {'VTV1': [{'thumb':'http://i.imgur.com/qrft7Fo.png',
					 'fanart':'http://i.imgur.com/FAQ7cXY.jpg'}
					 ],
				'VTV2':[{'thumb':'http://i.imgur.com/KOQDQD0.png',
					 'fanart':'http://i.imgur.com/FAQ7cXY.jpg'}
					 ],
				'VTV3':[{'thumb':'http://i.imgur.com/2hcarTN.png',
					 'fanart':'http://i.imgur.com/FAQ7cXY.jpg'}
					 ],
				'VTV4':[{'thumb':'http://i.imgur.com/UIAaZ2m.png',
					 'fanart':'http://i.imgur.com/FAQ7cXY.jpg'}
					 ],
				'VTV5':[{'thumb':'http://i.imgur.com/jJubbDC.png',
					 'fanart':'http://i.imgur.com/FAQ7cXY.jpg'}
					 ],
				'VTV6':[{'thumb':'http://i.imgur.com/sKFJL9y.png',
					 'fanart':'http://i.imgur.com/FAQ7cXY.jpg'}
					 ],
				'VTV7':[{'thumb':'http://i.imgur.com/PE88WhX.png',
					 'fanart':'http://i.imgur.com/FAQ7cXY.jpg'}
					 ],
				'VTV8':[{'thumb':'http://i.imgur.com/1huncz3.png',
					 'fanart':'http://i.imgur.com/FAQ7cXY.jpg'}
					 ],
				'VTV9':[{'thumb':'http://i.imgur.com/nmh9fG1.png',
					 'fanart':'http://i.imgur.com/FAQ7cXY.jpg'}
					 ]}